# Generated by Django 5.1.6 on 2025-02-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='1234567890', max_length=100),
        ),
    ]
