# Generated by Django 5.1.6 on 2025-02-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(),
        ),
    ]
