# Generated by Django 5.1.6 on 2025-02-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0009_alter_student_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
