# Generated by Django 5.0.4 on 2025-02-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0015_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
