# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-27 16:48
from __future__ import unicode_literals

from django.db import migrations
import flax_id.django.fields


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=flax_id.django.fields.FlaxId(editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
