# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-27 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_auto_20200527_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership', to='explore.Category'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='link_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
