# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_auto_20200527_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership', to='explore.Category'),
        ),
    ]
