# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_auto_20200528_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='category',
            field=models.ForeignKey(default='8vG0FKVTt8pJi4R1', on_delete=django.db.models.deletion.CASCADE, related_name='partnership', to='explore.Category'),
            preserve_default=False,
        ),
    ]
