# Generated by Django 5.1.6 on 2025-02-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_balance', models.IntegerField(default=0)),
            ],
        ),
    ]
