# Generated by Django 5.1.6 on 2025-02-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_balance', models.IntegerField(default=0)),
            ],
        ),
    ]
